
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/LocusAzzurro/Ultramarine/issues"
[[mods]]
modId="ultramarine"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_icon}"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''

[[dependencies.ultramarine]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ultramarine]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"